// CanvasRenderer.cpp — 2D HUD pass implementation.

#include "pch.h"
#include "CanvasRenderer.h"
#include "DeviceResources.h"
#include "PixMarkers.h"

// Compiled shader bytecode — generated by DXCCompile.
#include "CompiledShaders/CanvasVS.h"
#include "CompiledShaders/CanvasPS.h"

#include <cstring>
#include <algorithm>

namespace Neuron::Render
{

bool CanvasRenderer::Initialize(DeviceResources* dr)
{
    m_device = dr->Device();

    // --- Root signature: root constants — 2 floats (invScreenSize.xy) + 2 pad ---
    D3D12_ROOT_PARAMETER param{};
    param.ParameterType            = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    param.ShaderVisibility         = D3D12_SHADER_VISIBILITY_VERTEX;
    param.Constants.ShaderRegister = 0;
    param.Constants.RegisterSpace  = 0;
    param.Constants.Num32BitValues = 4; // float2 invScreenSize + float2 pad

    D3D12_ROOT_SIGNATURE_DESC rsDesc{};
    rsDesc.NumParameters = 1;
    rsDesc.pParameters   = &param;
    rsDesc.Flags         = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    winrt::com_ptr<ID3DBlob> sigBlob, errBlob;
    if (FAILED(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
                                           sigBlob.put(), errBlob.put())))
        return false;
    winrt::check_hresult(m_device->CreateRootSignature(
        0, sigBlob->GetBufferPointer(), sigBlob->GetBufferSize(),
        IID_PPV_ARGS(m_rootSig.put())));

    // --- Input layout: float2 pos + float4 color ---
    static constexpr D3D12_INPUT_ELEMENT_DESC kLayout[] = {
        { "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT,       0,  0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
        { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0,  8, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
    };

    // --- PSO: alpha-blend over the 3D scene, no depth test ---
    D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc{};
    psoDesc.pRootSignature        = m_rootSig.get();
    psoDesc.VS                    = { g_pCanvasVS, sizeof(g_pCanvasVS) };
    psoDesc.PS                    = { g_pCanvasPS, sizeof(g_pCanvasPS) };
    psoDesc.InputLayout           = { kLayout, static_cast<UINT>(std::size(kLayout)) };
    psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    psoDesc.NumRenderTargets      = 1;
    psoDesc.RTVFormats[0]         = DXGI_FORMAT_B8G8R8A8_UNORM;
    psoDesc.DSVFormat             = DXGI_FORMAT_D32_FLOAT;
    psoDesc.SampleMask            = 0xFFFFFFFFu;
    psoDesc.SampleDesc.Count      = 1;

    psoDesc.RasterizerState.FillMode              = D3D12_FILL_MODE_SOLID;
    psoDesc.RasterizerState.CullMode              = D3D12_CULL_MODE_NONE;
    psoDesc.RasterizerState.FrontCounterClockwise = FALSE;

    // Alpha blend: dst = src.a*src.rgb + (1-src.a)*dst.rgb
    auto& rt = psoDesc.BlendState.RenderTarget[0];
    rt.BlendEnable           = TRUE;
    rt.SrcBlend              = D3D12_BLEND_SRC_ALPHA;
    rt.DestBlend             = D3D12_BLEND_INV_SRC_ALPHA;
    rt.BlendOp               = D3D12_BLEND_OP_ADD;
    rt.SrcBlendAlpha         = D3D12_BLEND_ONE;
    rt.DestBlendAlpha        = D3D12_BLEND_ZERO;
    rt.BlendOpAlpha          = D3D12_BLEND_OP_ADD;
    rt.RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;

    psoDesc.DepthStencilState.DepthEnable = FALSE; // HUD draws over depth

    winrt::check_hresult(m_device->CreateGraphicsPipelineState(
        &psoDesc, IID_PPV_ARGS(m_pso.put())));

    // --- Dynamic vertex buffer (upload heap, persistently CPU-mapped) ---
    constexpr UINT64 vtxBufSize = kMaxQuads * 6 * sizeof(CanvasVertex);
    D3D12_HEAP_PROPERTIES hpUpload{};
    hpUpload.Type = D3D12_HEAP_TYPE_UPLOAD;
    D3D12_RESOURCE_DESC rd{};
    rd.Dimension        = D3D12_RESOURCE_DIMENSION_BUFFER;
    rd.Width            = vtxBufSize;
    rd.Height = rd.DepthOrArraySize = rd.MipLevels = 1;
    rd.SampleDesc.Count = 1;
    rd.Layout           = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    winrt::check_hresult(m_device->CreateCommittedResource(
        &hpUpload, D3D12_HEAP_FLAG_NONE, &rd,
        D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(m_vtxBuf.put())));
    D3D12_RANGE readRange{};
    winrt::check_hresult(m_vtxBuf->Map(0, &readRange,
        reinterpret_cast<void**>(&m_vtxPtr)));

    return true;
}

void CanvasRenderer::Uninitialize()
{
    if (m_vtxBuf && m_vtxPtr) { m_vtxBuf->Unmap(0, nullptr); m_vtxPtr = nullptr; }
}

void CanvasRenderer::Reset()
{
    m_vtxCount = 0;
}

void CanvasRenderer::AddQuad(float x, float y, float w, float h,
                              float r, float g, float b, float a)
{
    if (m_vtxCount + 6 > kMaxQuads * 6) return;
    auto* v = m_vtxPtr + m_vtxCount;
    // Two triangles, CCW, screen-space pixels
    v[0] = { x,   y,   r, g, b, a };
    v[1] = { x+w, y,   r, g, b, a };
    v[2] = { x+w, y+h, r, g, b, a };
    v[3] = { x,   y,   r, g, b, a };
    v[4] = { x+w, y+h, r, g, b, a };
    v[5] = { x,   y+h, r, g, b, a };
    m_vtxCount += 6;
}

void CanvasRenderer::DrawRect(float x, float y, float w, float h,
                               float r, float g, float b, float a)
{
    AddQuad(x, y, w, h, r, g, b, a);
}

void CanvasRenderer::DrawText(float x, float y, const char* text,
                               float r, float g, float b)
{
    // M1b placeholder: draw a narrow bar per character (8×12 px cells).
    // M2 replaces this with a font-atlas texture lookup.
    constexpr float kCharW = 8.f, kCharH = 12.f, kCharGap = 1.f;
    float cx = x;
    for (const char* p = text; *p; ++p) {
        if (*p != ' ')
            AddQuad(cx, y, kCharW, kCharH, r, g, b, 0.85f);
        cx += kCharW + kCharGap;
    }
}

void CanvasRenderer::Render(ID3D12GraphicsCommandList* cl,
                             UINT screenWidth, UINT screenHeight)
{
    if (!m_vtxCount) return;

    NEURON_PIX_SCOPED(cl, PixColors::Canvas, "Canvas HUD (%u verts)", m_vtxCount);

    cl->SetGraphicsRootSignature(m_rootSig.get());
    cl->SetPipelineState(m_pso.get());

    const float invSize[4] = { 1.f / screenWidth, 1.f / screenHeight, 0.f, 0.f };
    cl->SetGraphicsRoot32BitConstants(0, 4, invSize, 0);

    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    D3D12_VERTEX_BUFFER_VIEW vbView{
        m_vtxBuf->GetGPUVirtualAddress(),
        m_vtxCount * sizeof(CanvasVertex),
        sizeof(CanvasVertex)
    };
    cl->IASetVertexBuffers(0, 1, &vbView);
    cl->DrawInstanced(m_vtxCount, 1, 0, 0);
}

} // namespace Neuron::Render
