// CanvasRenderer.cpp — 2D HUD/UI pass: batched solid + textured + font primitives.

#include "pch.h"
#include "CanvasRenderer.h"
#include "DeviceResources.h"
#include "PixMarkers.h"

// Compiled shader bytecode — generated by DXCCompile.
#include "CompiledShaders/CanvasVS.h"
#include "CompiledShaders/CanvasPS.h"

#include <cstring>
#include <algorithm>

namespace Neuron::Render
{

bool CanvasRenderer::Initialize(DeviceResources* dr)
{
    m_device = dr->Device();

    // --- Root signature: b0 root constants (invScreenSize + mode) + SRV table t0
    //     + two static samplers (s0 linear chrome, s1 point font). ---
    D3D12_DESCRIPTOR_RANGE srvRange{};
    srvRange.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    srvRange.NumDescriptors = 1;
    srvRange.BaseShaderRegister = 0; // t0

    D3D12_ROOT_PARAMETER params[2]{};
    params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL; // VS reads size, PS reads mode
    params[0].Constants.ShaderRegister = 0; // b0
    params[0].Constants.Num32BitValues = 4; // invX, invY, mode, pad
    params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    params[1].DescriptorTable.NumDescriptorRanges = 1;
    params[1].DescriptorTable.pDescriptorRanges = &srvRange;

    D3D12_STATIC_SAMPLER_DESC samps[2]{};
    samps[0].Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR; // chrome gradient
    samps[0].AddressU = samps[0].AddressV = samps[0].AddressW = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    samps[0].MaxLOD = D3D12_FLOAT32_MAX;
    samps[0].ShaderRegister = 0; // s0
    samps[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    samps[1] = samps[0];
    samps[1].Filter = D3D12_FILTER_MIN_MAG_MIP_POINT; // crisp font
    samps[1].ShaderRegister = 1; // s1

    D3D12_ROOT_SIGNATURE_DESC rsDesc{};
    rsDesc.NumParameters = 2;
    rsDesc.pParameters = params;
    rsDesc.NumStaticSamplers = 2;
    rsDesc.pStaticSamplers = samps;
    rsDesc.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    winrt::com_ptr<ID3DBlob> sigBlob, errBlob;
    if (FAILED(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
                                           sigBlob.put(), errBlob.put())))
        return false;
    winrt::check_hresult(m_device->CreateRootSignature(
        0, sigBlob->GetBufferPointer(), sigBlob->GetBufferSize(),
        IID_PPV_ARGS(m_rootSig.put())));

    // --- Input layout: float2 pos + float2 uv + float4 color ---
    static constexpr D3D12_INPUT_ELEMENT_DESC kLayout[] = {
        { "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT,       0,  0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
        { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT,       0,  8, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
        { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 16, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
    };

    // --- PSO: alpha-blend over the scene, no depth ---
    D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc{};
    psoDesc.pRootSignature        = m_rootSig.get();
    psoDesc.VS                    = { g_pCanvasVS, sizeof(g_pCanvasVS) };
    psoDesc.PS                    = { g_pCanvasPS, sizeof(g_pCanvasPS) };
    psoDesc.InputLayout           = { kLayout, static_cast<UINT>(std::size(kLayout)) };
    psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    psoDesc.NumRenderTargets      = 1;
    psoDesc.RTVFormats[0]         = DXGI_FORMAT_B8G8R8A8_UNORM;
    psoDesc.DSVFormat             = DXGI_FORMAT_D32_FLOAT;
    psoDesc.SampleMask            = 0xFFFFFFFFu;
    psoDesc.SampleDesc.Count      = 1;

    psoDesc.RasterizerState.FillMode              = D3D12_FILL_MODE_SOLID;
    psoDesc.RasterizerState.CullMode              = D3D12_CULL_MODE_NONE;
    psoDesc.RasterizerState.FrontCounterClockwise = FALSE;

    auto& rt = psoDesc.BlendState.RenderTarget[0];
    rt.BlendEnable           = TRUE;
    rt.SrcBlend              = D3D12_BLEND_SRC_ALPHA;
    rt.DestBlend             = D3D12_BLEND_INV_SRC_ALPHA;
    rt.BlendOp               = D3D12_BLEND_OP_ADD;
    rt.SrcBlendAlpha         = D3D12_BLEND_ONE;
    rt.DestBlendAlpha        = D3D12_BLEND_ZERO;
    rt.BlendOpAlpha          = D3D12_BLEND_OP_ADD;
    rt.RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;

    psoDesc.DepthStencilState.DepthEnable = FALSE;

    winrt::check_hresult(m_device->CreateGraphicsPipelineState(
        &psoDesc, IID_PPV_ARGS(m_pso.put())));

    // --- Shader-visible SRV heap (font + chrome textures) ---
    D3D12_DESCRIPTOR_HEAP_DESC heapDesc{};
    heapDesc.NumDescriptors = kMaxTextures;
    heapDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
    heapDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
    winrt::check_hresult(m_device->CreateDescriptorHeap(&heapDesc, IID_PPV_ARGS(m_srvHeap.put())));
    m_srvSize = m_device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

    // --- Dynamic vertex buffer (upload heap, persistently CPU-mapped) ---
    constexpr UINT64 vtxBufSize = kMaxVerts * sizeof(CanvasVertex);
    D3D12_HEAP_PROPERTIES hpUpload{};
    hpUpload.Type = D3D12_HEAP_TYPE_UPLOAD;
    D3D12_RESOURCE_DESC rd{};
    rd.Dimension        = D3D12_RESOURCE_DIMENSION_BUFFER;
    rd.Width            = vtxBufSize;
    rd.Height = rd.DepthOrArraySize = rd.MipLevels = 1;
    rd.SampleDesc.Count = 1;
    rd.Layout           = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    winrt::check_hresult(m_device->CreateCommittedResource(
        &hpUpload, D3D12_HEAP_FLAG_NONE, &rd,
        D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(m_vtxBuf.put())));
    D3D12_RANGE readRange{};
    winrt::check_hresult(m_vtxBuf->Map(0, &readRange, reinterpret_cast<void**>(&m_vtxPtr)));

    return true;
}

void CanvasRenderer::Uninitialize()
{
    if (m_vtxBuf && m_vtxPtr) { m_vtxBuf->Unmap(0, nullptr); m_vtxPtr = nullptr; }
}

void CanvasRenderer::SetFont(TextureGpu font, er::format::FontAtlasConfig cfg)
{
    if (!font.valid()) return;
    m_font = std::move(font);
    m_fontCfg = cfg;
    m_fontSrv = EnsureSrv(m_font);
}

UINT CanvasRenderer::EnsureSrv(const TextureGpu& tex)
{
    auto it = m_srvByTex.find(tex.resource.get());
    if (it != m_srvByTex.end()) return it->second;
    if (m_nextSrv >= kMaxTextures) return 0; // out of slots: reuse slot 0 (font)

    const UINT idx = m_nextSrv++;
    D3D12_CPU_DESCRIPTOR_HANDLE h = m_srvHeap->GetCPUDescriptorHandleForHeapStart();
    h.ptr += static_cast<SIZE_T>(idx) * m_srvSize;

    D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
    srv.Format = tex.format;
    srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
    srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
    srv.Texture2D.MipLevels = tex.mipCount ? tex.mipCount : 1u;
    m_device->CreateShaderResourceView(tex.resource.get(), &srv, h);

    m_srvByTex[tex.resource.get()] = idx;
    return idx;
}

void CanvasRenderer::Reset()
{
    m_vtxCount = 0;
    m_batches.clear();
}

void CanvasRenderer::Prim(Mode mode, UINT srvIndex)
{
    if (m_batches.empty() || m_batches.back().mode != mode || m_batches.back().srvIndex != srvIndex)
        m_batches.push_back({ mode, srvIndex, m_vtxCount, 0 });
}

void CanvasRenderer::Vtx(float x, float y, float u, float v, float r, float g, float b, float a)
{
    if (m_vtxCount >= kMaxVerts) return;
    m_vtxPtr[m_vtxCount++] = { x, y, u, v, r, g, b, a };
    if (!m_batches.empty()) ++m_batches.back().count;
}

void CanvasRenderer::DrawRect(float x, float y, float w, float h, float r, float g, float b, float a)
{
    Prim(Mode::Solid, 0);
    Vtx(x,     y,     0, 0, r, g, b, a);
    Vtx(x + w, y,     0, 0, r, g, b, a);
    Vtx(x + w, y + h, 0, 0, r, g, b, a);
    Vtx(x,     y,     0, 0, r, g, b, a);
    Vtx(x + w, y + h, 0, 0, r, g, b, a);
    Vtx(x,     y + h, 0, 0, r, g, b, a);
}

void CanvasRenderer::DrawTriangle(float x0, float y0, float x1, float y1, float x2, float y2,
                                  float r, float g, float b, float a)
{
    Prim(Mode::Solid, 0);
    Vtx(x0, y0, 0, 0, r, g, b, a);
    Vtx(x1, y1, 0, 0, r, g, b, a);
    Vtx(x2, y2, 0, 0, r, g, b, a);
}

void CanvasRenderer::DrawTexturedQuad(float x, float y, float w, float h,
                                      float u0, float v0, float u1, float v1,
                                      const TextureGpu& tex, float r, float g, float b, float a)
{
    if (!tex.valid()) return;
    const UINT srv = EnsureSrv(tex);
    Prim(Mode::TexLinear, srv);
    Vtx(x,     y,     u0, v0, r, g, b, a);
    Vtx(x + w, y,     u1, v0, r, g, b, a);
    Vtx(x + w, y + h, u1, v1, r, g, b, a);
    Vtx(x,     y,     u0, v0, r, g, b, a);
    Vtx(x + w, y + h, u1, v1, r, g, b, a);
    Vtx(x,     y + h, u0, v1, r, g, b, a);
}

void CanvasRenderer::DrawText(float x, float y, const char* text, float r, float g, float b, float scale)
{
    if (!text || !m_font.valid()) return;
    const float cell = static_cast<float>(m_fontCfg.cellPx) * scale;
    float cx = x;
    for (const unsigned char* p = reinterpret_cast<const unsigned char*>(text); *p; ++p)
    {
        if (*p != ' ')
        {
            const auto uv = er::format::glyphUv(m_fontCfg, *p);
            Prim(Mode::TexPoint, m_fontSrv);
            Vtx(cx,        y,        uv.u0, uv.v0, r, g, b, 1.f);
            Vtx(cx + cell, y,        uv.u1, uv.v0, r, g, b, 1.f);
            Vtx(cx + cell, y + cell, uv.u1, uv.v1, r, g, b, 1.f);
            Vtx(cx,        y,        uv.u0, uv.v0, r, g, b, 1.f);
            Vtx(cx + cell, y + cell, uv.u1, uv.v1, r, g, b, 1.f);
            Vtx(cx,        y + cell, uv.u0, uv.v1, r, g, b, 1.f);
        }
        cx += cell;
    }
}

float CanvasRenderer::TextWidth(const char* text, float scale) const
{
    if (!text) return 0.f;
    return static_cast<float>(std::strlen(text)) * static_cast<float>(m_fontCfg.cellPx) * scale;
}

float CanvasRenderer::TextHeight(float scale) const
{
    return static_cast<float>(m_fontCfg.cellPx) * scale;
}

void CanvasRenderer::Render(ID3D12GraphicsCommandList* cl, UINT screenWidth, UINT screenHeight)
{
    if (!m_vtxCount || m_batches.empty() || m_nextSrv == 0) return;

    NEURON_PIX_SCOPED(cl, PixColors::Canvas, "Canvas UI (%u verts, %zu batches)",
                      m_vtxCount, m_batches.size());

    cl->SetGraphicsRootSignature(m_rootSig.get());
    cl->SetPipelineState(m_pso.get());
    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    ID3D12DescriptorHeap* heaps[] = { m_srvHeap.get() };
    cl->SetDescriptorHeaps(1, heaps);

    D3D12_VERTEX_BUFFER_VIEW vbView{
        m_vtxBuf->GetGPUVirtualAddress(),
        m_vtxCount * static_cast<UINT>(sizeof(CanvasVertex)),
        static_cast<UINT>(sizeof(CanvasVertex))
    };
    cl->IASetVertexBuffers(0, 1, &vbView);

    const float invW = screenWidth ? 1.f / static_cast<float>(screenWidth) : 0.f;
    const float invH = screenHeight ? 1.f / static_cast<float>(screenHeight) : 0.f;

    for (const Batch& b : m_batches)
    {
        if (!b.count) continue;
        const float consts[4] = { invW, invH, static_cast<float>(b.mode), 0.f };
        cl->SetGraphicsRoot32BitConstants(0, 4, consts, 0);

        D3D12_GPU_DESCRIPTOR_HANDLE srv = m_srvHeap->GetGPUDescriptorHandleForHeapStart();
        srv.ptr += static_cast<UINT64>(b.srvIndex) * m_srvSize;
        cl->SetGraphicsRootDescriptorTable(1, srv);

        cl->DrawInstanced(b.count, 1, b.start, 0);
    }
}

} // namespace Neuron::Render
