// NeuronRender.cpp — single compile-unit stub for the NeuronRender static library.
//
// All renderer classes are compiled via their own .cpp files listed in
// NeuronRender.vcxproj; this file just documents what is in the library.
//
// Subsystems:
//   gfx/DeviceResources  — D3D12 device, swap chain, command infrastructure
//   scene/SceneRenderer  — 3D instanced geometry pass (SM6 shaders)
//   canvas/CanvasRenderer— 2D HUD pass (immediate-mode quads)
//
// Compiled shaders (generated by DXCCompile at build time; not in source control):
//   CompiledShaders/SceneVS.h, ScenePS.h, CanvasVS.h, CanvasPS.h

#include "gfx/DeviceResources.h"
#include "scene/SceneRenderer.h"
#include "canvas/CanvasRenderer.h"
