// PostProcess.cpp — HDR + bloom + composite implementation (M2 area C).

#include "pch.h"
#include "PostProcess.h"
#include "DeviceResources.h"
#include "PixMarkers.h"

// Compiled shader bytecode — generated by DXCCompile (NeuronRender.vcxproj).
#include "CompiledShaders/FullscreenVS.h"
#include "CompiledShaders/BrightPassPS.h"
#include "CompiledShaders/BlurPS.h"
#include "CompiledShaders/CompositePS.h"

namespace Neuron::Render
{
  namespace
  {
    // Bloom + tone-map tunables.
    constexpr float THRESHOLD = 0.60f; // luminance above which bloom is extracted
    constexpr float INTENSITY = 1.10f; // bloom add strength in the composite
    constexpr float EXPOSURE  = 1.30f; // scene exposure before the ACES tone-map
    constexpr float VIGNETTE  = 0.32f; // corner darkening (Darwinia framing)
    constexpr float SCANLINE  = 0.05f; // faint CRT scanlines (0 = off)
  } // namespace

  bool PostProcess::Initialize(DeviceResources* dr)
  {
    m_dr = dr;
    m_device = dr->Device();

    // --- Shared root signature: root constants b0 (4 floats) + two single-SRV
    //     tables (t0 source, t1 bloom) + static linear-clamp sampler s0. ---
    D3D12_DESCRIPTOR_RANGE rangeT0{};
    rangeT0.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    rangeT0.NumDescriptors = 1;
    rangeT0.BaseShaderRegister = 0; // t0
    D3D12_DESCRIPTOR_RANGE rangeT1 = rangeT0;
    rangeT1.BaseShaderRegister = 1; // t1

    D3D12_ROOT_PARAMETER params[3]{};
    params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    params[0].Constants.ShaderRegister = 0; // b0
    params[0].Constants.Num32BitValues = 4;
    params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    params[1].DescriptorTable.NumDescriptorRanges = 1;
    params[1].DescriptorTable.pDescriptorRanges = &rangeT0;
    params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    params[2].DescriptorTable.NumDescriptorRanges = 1;
    params[2].DescriptorTable.pDescriptorRanges = &rangeT1;

    D3D12_STATIC_SAMPLER_DESC samp{};
    samp.Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
    samp.AddressU = samp.AddressV = samp.AddressW = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    samp.MaxLOD = D3D12_FLOAT32_MAX;
    samp.ShaderRegister = 0; // s0
    samp.ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;

    D3D12_ROOT_SIGNATURE_DESC rs{};
    rs.NumParameters = 3;
    rs.pParameters = params;
    rs.NumStaticSamplers = 1;
    rs.pStaticSamplers = &samp;
    rs.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

    winrt::com_ptr<ID3DBlob> sigBlob, errBlob;
    if (FAILED(D3D12SerializeRootSignature(&rs, D3D_ROOT_SIGNATURE_VERSION_1, sigBlob.put(), errBlob.put())))
      return false;
    if (FAILED(m_device->CreateRootSignature(0, sigBlob->GetBufferPointer(), sigBlob->GetBufferSize(),
                                             IID_PPV_ARGS(m_rootSig.put()))))
      return false;

    // --- PSOs: a full-screen triangle (no input layout / vertex buffer), solid,
    //     no cull, depth disabled. Bright/Blur write HDR; Composite writes LDR. ---
    auto makePso = [&](const void* psBytes, SIZE_T psSize, DXGI_FORMAT rtFormat, DXGI_FORMAT dsFormat,
                       winrt::com_ptr<ID3D12PipelineState>& out) -> bool
    {
      D3D12_GRAPHICS_PIPELINE_STATE_DESC d{};
      d.pRootSignature = m_rootSig.get();
      d.VS = {g_pFullscreenVS, sizeof(g_pFullscreenVS)};
      d.PS = {psBytes, psSize};
      d.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
      d.NumRenderTargets = 1;
      d.RTVFormats[0] = rtFormat;
      d.DSVFormat = dsFormat;
      d.SampleMask = 0xFFFFFFFFu;
      d.SampleDesc.Count = 1;
      d.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
      d.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
      d.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
      d.DepthStencilState.DepthEnable = FALSE;
      d.DepthStencilState.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ZERO;
      return SUCCEEDED(m_device->CreateGraphicsPipelineState(&d, IID_PPV_ARGS(out.put())));
    };

    if (!makePso(g_pBrightPassPS, sizeof(g_pBrightPassPS), HDR_FORMAT, DXGI_FORMAT_UNKNOWN, m_psoBright))
      return false;
    if (!makePso(g_pBlurPS, sizeof(g_pBlurPS), HDR_FORMAT, DXGI_FORMAT_UNKNOWN, m_psoBlur))
      return false;
    // Composite targets the LDR swap-chain buffer and runs with the shared depth
    // bound (test disabled), matching the HUD pass that draws over it.
    if (!makePso(g_pCompositePS, sizeof(g_pCompositePS), DXGI_FORMAT_B8G8R8A8_UNORM, DXGI_FORMAT_D32_FLOAT,
                 m_psoComposite))
      return false;

    // --- Descriptor heaps: 3 RTVs (CPU) + 3 SRVs (shader-visible). ---
    D3D12_DESCRIPTOR_HEAP_DESC rtvDesc{};
    rtvDesc.NumDescriptors = 3;
    rtvDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
    if (FAILED(m_device->CreateDescriptorHeap(&rtvDesc, IID_PPV_ARGS(m_rtvHeap.put()))))
      return false;
    m_rtvSize = m_device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);

    D3D12_DESCRIPTOR_HEAP_DESC srvDesc{};
    srvDesc.NumDescriptors = 3;
    srvDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
    srvDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
    if (FAILED(m_device->CreateDescriptorHeap(&srvDesc, IID_PPV_ARGS(m_srvHeap.put()))))
      return false;
    m_srvSize = m_device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

    // Fixed SRV-heap slots (composite reads HDR=0 and bloomA=1).
    m_hdr.srvIndex = 0;
    m_bloomA.srvIndex = 1;
    m_bloomB.srvIndex = 2;

    if (!CreateTargets())
      return false;

    m_ready = true;
    return true;
  }

  bool PostProcess::CreateTargets()
  {
    m_width = m_dr->Width();
    m_height = m_dr->Height();
    m_halfW = (m_width + 1) / 2;
    m_halfH = (m_height + 1) / 2;
    if (!m_width || !m_height)
      return false;

    auto rtvCpu = [&](UINT i)
    {
      D3D12_CPU_DESCRIPTOR_HANDLE h = m_rtvHeap->GetCPUDescriptorHandleForHeapStart();
      h.ptr += static_cast<SIZE_T>(i) * m_rtvSize;
      return h;
    };
    auto srvCpu = [&](UINT i)
    {
      D3D12_CPU_DESCRIPTOR_HANDLE h = m_srvHeap->GetCPUDescriptorHandleForHeapStart();
      h.ptr += static_cast<SIZE_T>(i) * m_srvSize;
      return h;
    };

    auto makeTarget = [&](Target& t, UINT w, UINT h, UINT rtvSlot) -> bool
    {
      t.res = nullptr; // release any previous (resize)
      D3D12_HEAP_PROPERTIES hp{};
      hp.Type = D3D12_HEAP_TYPE_DEFAULT;
      D3D12_RESOURCE_DESC rd{};
      rd.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
      rd.Width = w;
      rd.Height = h;
      rd.DepthOrArraySize = 1;
      rd.MipLevels = 1;
      rd.Format = HDR_FORMAT;
      rd.SampleDesc.Count = 1;
      rd.Flags = D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;

      D3D12_CLEAR_VALUE cv{};
      cv.Format = HDR_FORMAT;
      cv.Color[0] = 0.018f;
      cv.Color[1] = 0.014f;
      cv.Color[2] = 0.013f;
      cv.Color[3] = 1.0f;

      if (FAILED(m_device->CreateCommittedResource(&hp, D3D12_HEAP_FLAG_NONE, &rd,
                                                   D3D12_RESOURCE_STATE_COMMON, &cv,
                                                   IID_PPV_ARGS(t.res.put()))))
        return false;
      t.state = D3D12_RESOURCE_STATE_COMMON;
      t.rtv = rtvCpu(rtvSlot);
      m_device->CreateRenderTargetView(t.res.get(), nullptr, t.rtv);

      D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
      srv.Format = HDR_FORMAT;
      srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
      srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
      srv.Texture2D.MipLevels = 1;
      m_device->CreateShaderResourceView(t.res.get(), &srv, srvCpu(t.srvIndex));
      return true;
    };

    return makeTarget(m_hdr, m_width, m_height, 0) &&
           makeTarget(m_bloomA, m_halfW, m_halfH, 1) &&
           makeTarget(m_bloomB, m_halfW, m_halfH, 2);
  }

  void PostProcess::Resize()
  {
    if (!m_ready)
      return;
    // GPU is idle here (App calls Resize after DeviceResources::Resize, which
    // waits for the GPU), so recreating the targets in place is safe.
    if (!CreateTargets())
      m_ready = false;
  }

  void PostProcess::Uninitialize()
  {
    m_ready = false;
  }

  D3D12_GPU_DESCRIPTOR_HANDLE PostProcess::SrvGpu(UINT index) const
  {
    D3D12_GPU_DESCRIPTOR_HANDLE h = m_srvHeap->GetGPUDescriptorHandleForHeapStart();
    h.ptr += static_cast<UINT64>(index) * m_srvSize;
    return h;
  }

  void PostProcess::Barrier(ID3D12GraphicsCommandList* cl, Target& t, D3D12_RESOURCE_STATES to)
  {
    if (t.state == to)
      return;
    D3D12_RESOURCE_BARRIER rb{};
    rb.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    rb.Transition.pResource = t.res.get();
    rb.Transition.StateBefore = t.state;
    rb.Transition.StateAfter = to;
    rb.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    cl->ResourceBarrier(1, &rb);
    t.state = to;
  }

  void PostProcess::BeginScene(ID3D12GraphicsCommandList* cl)
  {
    if (!m_ready)
      return;
    NEURON_PIX_SCOPED(cl, PixColors::Scene, "HDR scene begin");

    Barrier(cl, m_hdr, D3D12_RESOURCE_STATE_RENDER_TARGET);

    const D3D12_CPU_DESCRIPTOR_HANDLE dsv = m_dr->DsvHandle();
    cl->OMSetRenderTargets(1, &m_hdr.rtv, FALSE, &dsv);

    constexpr float SKY[] = {0.018f, 0.014f, 0.013f, 1.0f}; // near-black warm void
    cl->ClearRenderTargetView(m_hdr.rtv, SKY, 0, nullptr);
    // Depth was already cleared by DeviceResources::BeginFrame; the scene draws
    // into the HDR target using the shared depth buffer.

    D3D12_VIEWPORT vp{0.f, 0.f, static_cast<float>(m_width), static_cast<float>(m_height), 0.f, 1.f};
    D3D12_RECT sr{0, 0, static_cast<LONG>(m_width), static_cast<LONG>(m_height)};
    cl->RSSetViewports(1, &vp);
    cl->RSSetScissorRects(1, &sr);
  }

  void PostProcess::DrawFullscreen(ID3D12GraphicsCommandList* cl, ID3D12PipelineState* pso, Target& dst,
                                   UINT srcSrvIndex, UINT bloomSrvIndex, const float params[4], UINT vpW,
                                   UINT vpH)
  {
    Barrier(cl, dst, D3D12_RESOURCE_STATE_RENDER_TARGET);
    cl->OMSetRenderTargets(1, &dst.rtv, FALSE, nullptr);

    D3D12_VIEWPORT vp{0.f, 0.f, static_cast<float>(vpW), static_cast<float>(vpH), 0.f, 1.f};
    D3D12_RECT sr{0, 0, static_cast<LONG>(vpW), static_cast<LONG>(vpH)};
    cl->RSSetViewports(1, &vp);
    cl->RSSetScissorRects(1, &sr);

    cl->SetPipelineState(pso);
    cl->SetGraphicsRoot32BitConstants(0, 4, params, 0);
    cl->SetGraphicsRootDescriptorTable(1, SrvGpu(srcSrvIndex));
    cl->SetGraphicsRootDescriptorTable(2, SrvGpu(bloomSrvIndex));
    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    cl->DrawInstanced(3, 1, 0, 0);
  }

  void PostProcess::Resolve(ID3D12GraphicsCommandList* cl)
  {
    if (!m_ready)
      return;
    NEURON_PIX_SCOPED(cl, PixColors::Scene, "Bloom + composite");

    ID3D12DescriptorHeap* heaps[] = {m_srvHeap.get()};
    cl->SetDescriptorHeaps(1, heaps);
    cl->SetGraphicsRootSignature(m_rootSig.get());

    // Scene left the HDR target as RENDER_TARGET; make it sampleable.
    Barrier(cl, m_hdr, D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);

    // Bright-pass + downsample: HDR (t0) -> bloomA (half-res).
    const float pBright[4] = {THRESHOLD, 0.f, 0.f, 0.f};
    DrawFullscreen(cl, m_psoBright.get(), m_bloomA, m_hdr.srvIndex, m_hdr.srvIndex, pBright, m_halfW, m_halfH);

    // Separable Gaussian: horizontal bloomA -> bloomB, then vertical bloomB -> bloomA.
    Barrier(cl, m_bloomA, D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);
    const float pH[4] = {0.f, 0.f, 1.f / static_cast<float>(m_halfW), 0.f};
    DrawFullscreen(cl, m_psoBlur.get(), m_bloomB, m_bloomA.srvIndex, m_hdr.srvIndex, pH, m_halfW, m_halfH);

    Barrier(cl, m_bloomB, D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);
    const float pV[4] = {0.f, 0.f, 0.f, 1.f / static_cast<float>(m_halfH)};
    DrawFullscreen(cl, m_psoBlur.get(), m_bloomA, m_bloomB.srvIndex, m_hdr.srvIndex, pV, m_halfW, m_halfH);

    // Composite HDR (t0) + bloomA (t1) into the back buffer (full-res).
    Barrier(cl, m_bloomA, D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);

    const D3D12_CPU_DESCRIPTOR_HANDLE rtv = m_dr->RtvHandle();
    const D3D12_CPU_DESCRIPTOR_HANDLE dsv = m_dr->DsvHandle();
    cl->OMSetRenderTargets(1, &rtv, FALSE, &dsv);

    D3D12_VIEWPORT vp{0.f, 0.f, static_cast<float>(m_width), static_cast<float>(m_height), 0.f, 1.f};
    D3D12_RECT sr{0, 0, static_cast<LONG>(m_width), static_cast<LONG>(m_height)};
    cl->RSSetViewports(1, &vp);
    cl->RSSetScissorRects(1, &sr);

    const float pComp[4] = {EXPOSURE, m_bloomIntensity,
                            m_pixelEffect ? VIGNETTE : 0.f,
                            m_pixelEffect ? SCANLINE : 0.f};
    cl->SetPipelineState(m_psoComposite.get());
    cl->SetGraphicsRoot32BitConstants(0, 4, pComp, 0);
    cl->SetGraphicsRootDescriptorTable(1, SrvGpu(m_hdr.srvIndex));
    cl->SetGraphicsRootDescriptorTable(2, SrvGpu(m_bloomA.srvIndex));
    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    cl->DrawInstanced(3, 1, 0, 0);
    // Back buffer + depth remain bound so the HUD draws over the composite.
  }
} // namespace Neuron::Render
