// SceneRenderer.cpp — 3D instanced scene pass implementation.

#include "pch.h"
#include "SceneRenderer.h"
#include "DeviceResources.h"
#include "PixMarkers.h"

// Compiled shader bytecode — generated by DXCCompile (NeuronRender.vcxproj).
// These headers are build artifacts; not checked into source control.
#include "CompiledShaders/SceneVS.h"
#include "CompiledShaders/ScenePS.h"
#include "CompiledShaders/SceneTexVS.h"
#include "CompiledShaders/SceneTexPS.h"

#include <algorithm>
#include <DirectXMath.h>
#include <cmath>
#include <cstring>

using namespace DirectX;

namespace Neuron::Render
{
  // ---------------------------------------------------------------------------
  // Unit cube geometry (1m half-extent → callers apply scale in the world matrix)
  // ---------------------------------------------------------------------------
  // Face winding: front = CCW; cull mode = back.
  // 24 vertices (4 unique per face × 6 faces), 36 indices.
  struct CubeVertex
  {
    float px, py, pz, nx, ny, nz;
  };

  static void FillCube(CubeVertex* verts, UINT16* idx)
  {
    // Helper: add one quad (2 triangles, CCW front face)
    UINT16 vi = 0, ii = 0;
    auto quad = [&](const XMFLOAT3& a, const XMFLOAT3& b, const XMFLOAT3& c, const XMFLOAT3& d, const XMFLOAT3& n)
    {
      UINT16 base = vi;
      for (const auto& p : {a, b, c, d})
      {
        verts[vi++] = {p.x, p.y, p.z, n.x, n.y, n.z};
      }
      idx[ii++] = base;
      idx[ii++] = base + 1;
      idx[ii++] = base + 2;
      idx[ii++] = base;
      idx[ii++] = base + 2;
      idx[ii++] = base + 3;
    };
    // +X face
    quad({1, -1, 1}, {1, 1, 1}, {1, 1, -1}, {1, -1, -1}, {1, 0, 0});
    // -X face
    quad({-1, -1, -1}, {-1, 1, -1}, {-1, 1, 1}, {-1, -1, 1}, {-1, 0, 0});
    // +Y face
    quad({-1, 1, 1}, {1, 1, 1}, {1, 1, -1}, {-1, 1, -1}, {0, 1, 0});
    // -Y face
    quad({-1, -1, -1}, {1, -1, -1}, {1, -1, 1}, {-1, -1, 1}, {0, -1, 0});
    // +Z face
    quad({-1, -1, 1}, {1, -1, 1}, {1, 1, 1}, {-1, 1, 1}, {0, 0, 1});
    // -Z face
    quad({1, -1, -1}, {-1, -1, -1}, {-1, 1, -1}, {1, 1, -1}, {0, 0, -1});
  }

  // ---------------------------------------------------------------------------
  // Helper: create a GPU buffer from a CPU blob using a temporary upload heap.
  // ---------------------------------------------------------------------------
  static winrt::com_ptr<ID3D12Resource> CreateBufferWithData(ID3D12Device* device, ID3D12GraphicsCommandList* cl,
                                                             const void* data, UINT64 size,
                                                             D3D12_RESOURCE_STATES finalState,
                                                             winrt::com_ptr<ID3D12Resource>& uploadOut)
  {
    // Default heap (GPU only)
    D3D12_HEAP_PROPERTIES hpDefault{};
    hpDefault.Type = D3D12_HEAP_TYPE_DEFAULT;
    D3D12_RESOURCE_DESC rd{};
    rd.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    rd.Width = size;
    rd.Height = rd.DepthOrArraySize = rd.MipLevels = 1;
    rd.SampleDesc.Count = 1;
    rd.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

    winrt::com_ptr<ID3D12Resource> buf;
    winrt::check_hresult(device->CreateCommittedResource(&hpDefault, D3D12_HEAP_FLAG_NONE, &rd,
                                                         D3D12_RESOURCE_STATE_COMMON, nullptr,
                                                         IID_PPV_ARGS(buf.put())));

    // Upload heap (CPU write → GPU copy)
    D3D12_HEAP_PROPERTIES hpUpload{};
    hpUpload.Type = D3D12_HEAP_TYPE_UPLOAD;
    winrt::check_hresult(device->CreateCommittedResource(&hpUpload, D3D12_HEAP_FLAG_NONE, &rd,
                                                         D3D12_RESOURCE_STATE_GENERIC_READ, nullptr,
                                                         IID_PPV_ARGS(uploadOut.put())));

    void* mapped = nullptr;
    D3D12_RANGE readRange{};
    winrt::check_hresult(uploadOut->Map(0, &readRange, &mapped));
    std::memcpy(mapped, data, size);
    uploadOut->Unmap(0, nullptr);

    D3D12_RESOURCE_BARRIER rb{};
    rb.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    rb.Transition.pResource = buf.get();
    rb.Transition.StateBefore = D3D12_RESOURCE_STATE_COMMON;
    rb.Transition.StateAfter = D3D12_RESOURCE_STATE_COPY_DEST;
    rb.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    cl->ResourceBarrier(1, &rb);

    cl->CopyResource(buf.get(), uploadOut.get());

    rb.Transition.StateBefore = D3D12_RESOURCE_STATE_COPY_DEST;
    rb.Transition.StateAfter = finalState;
    cl->ResourceBarrier(1, &rb);

    return buf;
  }

  // ---------------------------------------------------------------------------
  // Initialize
  // ---------------------------------------------------------------------------
  bool SceneRenderer::Initialize(DeviceResources* dr, DXGI_FORMAT sceneColorFormat)
  {
    m_dr = dr;
    m_device = dr->Device();

    // --- Root signature: b0 viewProj (VS, 16 floats) + b1 lighting (PS, 16) ---
    D3D12_ROOT_PARAMETER param[2]{};
    param[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    param[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_VERTEX;
    param[0].Constants.ShaderRegister = 0; // b0
    param[0].Constants.Num32BitValues = 16;
    param[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    param[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    param[1].Constants.ShaderRegister = 1; // b1 (Lighting.hlsli)
    param[1].Constants.Num32BitValues = 28;

    D3D12_ROOT_SIGNATURE_DESC rsDesc{};
    rsDesc.NumParameters = 2;
    rsDesc.pParameters = param;
    rsDesc.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    winrt::com_ptr<ID3DBlob> sigBlob, errBlob;
    if (FAILED(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1, sigBlob.put(), errBlob.put()))) return
      false;
    winrt::check_hresult(m_device->CreateRootSignature(0, sigBlob->GetBufferPointer(), sigBlob->GetBufferSize(),
                                                       IID_PPV_ARGS(m_rootSig.put())));

    // --- Input layout ---
    static constexpr D3D12_INPUT_ELEMENT_DESC kLayout[] = {
      // Stream 0: per-vertex
      {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
      {"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
      // Stream 1: per-instance (world matrix rows w0-w3 + color)
      {"TEXCOORD", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 0, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
      {"TEXCOORD", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 16, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
      {"TEXCOORD", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 32, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
      {"TEXCOORD", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 48, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
      {"COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 64, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
    };

    // --- PSO ---
    D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc{};
    psoDesc.pRootSignature = m_rootSig.get();
    psoDesc.VS = {g_pSceneVS, sizeof(g_pSceneVS)};
    psoDesc.PS = {g_pScenePS, sizeof(g_pScenePS)};
    psoDesc.InputLayout = {kLayout, static_cast<UINT>(std::size(kLayout))};
    psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    psoDesc.NumRenderTargets = 1;
    psoDesc.RTVFormats[0] = sceneColorFormat;
    psoDesc.DSVFormat = DXGI_FORMAT_D32_FLOAT;
    psoDesc.SampleMask = 0xFFFFFFFFu;
    psoDesc.SampleDesc.Count = 1;

    // Rasterizer: solid, no culling. Authored CMO winding varies (and may differ
    // from the placeholder cube), so cull nothing to avoid an inside-out mesh.
    psoDesc.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
    psoDesc.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
    psoDesc.RasterizerState.FrontCounterClockwise = FALSE;
    psoDesc.RasterizerState.DepthClipEnable = TRUE;

    // Blend: opaque
    psoDesc.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;

    // Depth: test + write
    psoDesc.DepthStencilState.DepthEnable = TRUE;
    psoDesc.DepthStencilState.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ALL;
    psoDesc.DepthStencilState.DepthFunc = D3D12_COMPARISON_FUNC_LESS;

    winrt::check_hresult(m_device->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(m_pso.put())));

    // --- Textured pipeline (root constants + diffuse SRV table + static sampler) ---
    {
      D3D12_DESCRIPTOR_RANGE srvRange{};
      srvRange.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
      srvRange.NumDescriptors = 1;
      srvRange.BaseShaderRegister = 0; // t0

      D3D12_ROOT_PARAMETER params[3]{};
      params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
      params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_VERTEX;
      params[0].Constants.ShaderRegister = 0; // b0 viewProj
      params[0].Constants.Num32BitValues = 16;
      params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
      params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
      params[1].DescriptorTable.NumDescriptorRanges = 1;
      params[1].DescriptorTable.pDescriptorRanges = &srvRange;
      params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
      params[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
      params[2].Constants.ShaderRegister = 1; // b1 lighting (Lighting.hlsli)
      params[2].Constants.Num32BitValues = 28;

      D3D12_STATIC_SAMPLER_DESC samp{};
      samp.Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
      samp.AddressU = samp.AddressV = samp.AddressW = D3D12_TEXTURE_ADDRESS_MODE_WRAP;
      samp.MaxLOD = D3D12_FLOAT32_MAX;
      samp.ShaderRegister = 0; // s0
      samp.ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;

      D3D12_ROOT_SIGNATURE_DESC rsTex{};
      rsTex.NumParameters = 3;
      rsTex.pParameters = params;
      rsTex.NumStaticSamplers = 1;
      rsTex.pStaticSamplers = &samp;
      rsTex.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

      winrt::com_ptr<ID3DBlob> texSig, texErr;
      winrt::check_hresult(
          D3D12SerializeRootSignature(&rsTex, D3D_ROOT_SIGNATURE_VERSION_1, texSig.put(), texErr.put()));
      winrt::check_hresult(m_device->CreateRootSignature(0, texSig->GetBufferPointer(),
                                                         texSig->GetBufferSize(),
                                                         IID_PPV_ARGS(m_rootSigTex.put())));

      // Textured input layout: stream-0 adds the per-vertex UV (CMO offset 44).
      static constexpr D3D12_INPUT_ELEMENT_DESC kLayoutTex[] = {
        {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
        {"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
        {"TEXCOORD", 4, DXGI_FORMAT_R32G32_FLOAT, 0, 44, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
        {"TEXCOORD", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 0, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
        {"TEXCOORD", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 16, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
        {"TEXCOORD", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 32, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
        {"TEXCOORD", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 48, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
        {"COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 64, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1},
      };
      D3D12_GRAPHICS_PIPELINE_STATE_DESC texPso = psoDesc; // inherit RT/DS/raster/blend
      texPso.pRootSignature = m_rootSigTex.get();
      texPso.VS = {g_pSceneTexVS, sizeof(g_pSceneTexVS)};
      texPso.PS = {g_pSceneTexPS, sizeof(g_pSceneTexPS)};
      texPso.InputLayout = {kLayoutTex, static_cast<UINT>(std::size(kLayoutTex))};
      winrt::check_hresult(m_device->CreateGraphicsPipelineState(&texPso, IID_PPV_ARGS(m_psoTex.put())));

      D3D12_DESCRIPTOR_HEAP_DESC srvHeapDesc{};
      srvHeapDesc.NumDescriptors = kMaxShapes; // one diffuse SRV per registered shape
      srvHeapDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
      srvHeapDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
      winrt::check_hresult(m_device->CreateDescriptorHeap(&srvHeapDesc, IID_PPV_ARGS(m_srvHeap.put())));
      m_srvDescSize = m_device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    }

    // --- Upload geometry via a temporary command list ---
    // (Caller runs us inside the frame's command list which is open at Initialize time;
    //  we re-open and execute a separate one to keep the geometry upload atomic.)
    winrt::com_ptr<ID3D12CommandAllocator> uploadAlloc;
    winrt::check_hresult(m_device->CreateCommandAllocator(
      D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(uploadAlloc.put())));
    winrt::com_ptr<ID3D12GraphicsCommandList> uploadCl;
    winrt::check_hresult(m_device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, uploadAlloc.get(), nullptr,
                                                     IID_PPV_ARGS(uploadCl.put())));

    // Build cube CPU data
    static CubeVertex cubeVerts[24];
    static UINT16 cubeIdx[36];
    FillCube(cubeVerts, cubeIdx);
    m_indexCount = 36;

    NEURON_PIX_BEGIN(uploadCl.get(), PixColors::Upload, "SceneRenderer geometry upload");
    winrt::com_ptr<ID3D12Resource> vbUpload, ibUpload;
    m_vb = CreateBufferWithData(m_device, uploadCl.get(), cubeVerts, sizeof(cubeVerts),
                                D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER, vbUpload);
    m_ib = CreateBufferWithData(m_device, uploadCl.get(), cubeIdx, sizeof(cubeIdx), D3D12_RESOURCE_STATE_INDEX_BUFFER,
                                ibUpload);
    NEURON_PIX_END(uploadCl.get());

    winrt::check_hresult(uploadCl->Close());

    // Execute and wait for the upload to complete
    winrt::com_ptr<ID3D12CommandQueue> tmpQueue;
    D3D12_COMMAND_QUEUE_DESC qd{};
    qd.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
    winrt::check_hresult(m_device->CreateCommandQueue(&qd, IID_PPV_ARGS(tmpQueue.put())));
    ID3D12CommandList* lists[] = {uploadCl.get()};
    tmpQueue->ExecuteCommandLists(1, lists);
    winrt::com_ptr<ID3D12Fence> fence;
    winrt::check_hresult(m_device->CreateFence(0, D3D12_FENCE_FLAG_NONE, IID_PPV_ARGS(fence.put())));
    HANDLE ev = CreateEventW(nullptr, FALSE, FALSE, nullptr);
    winrt::check_hresult(tmpQueue->Signal(fence.get(), 1));
    winrt::check_hresult(fence->SetEventOnCompletion(1, ev));
    WaitForSingleObjectEx(ev, INFINITE, FALSE);
    CloseHandle(ev);

    // Set up static VB/IB views
    m_vbView = {m_vb->GetGPUVirtualAddress(), sizeof(cubeVerts), sizeof(Vertex)};
    m_ibView = {m_ib->GetGPUVirtualAddress(), sizeof(cubeIdx), DXGI_FORMAT_R16_UINT};

    // --- Per-instance upload buffers (one per in-flight frame, CPU-mapped) ---
    constexpr UINT64 instBufSize = kMaxEntities * sizeof(InstanceData);
    D3D12_HEAP_PROPERTIES hpUpload{};
    hpUpload.Type = D3D12_HEAP_TYPE_UPLOAD;
    D3D12_RESOURCE_DESC instDesc{};
    instDesc.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    instDesc.Width = instBufSize;
    instDesc.Height = instDesc.DepthOrArraySize = instDesc.MipLevels = 1;
    instDesc.SampleDesc.Count = 1;
    instDesc.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    for (UINT i = 0; i < DeviceResources::kFrameCount; ++i)
    {
      winrt::check_hresult(m_device->CreateCommittedResource(&hpUpload, D3D12_HEAP_FLAG_NONE, &instDesc,
                                                             D3D12_RESOURCE_STATE_GENERIC_READ, nullptr,
                                                             IID_PPV_ARGS(m_instBuf[i].put())));
      D3D12_RANGE readRange{};
      winrt::check_hresult(m_instBuf[i]->Map(0, &readRange, reinterpret_cast<void**>(&m_instPtr[i])));
      m_instView[i] = {m_instBuf[i]->GetGPUVirtualAddress(), static_cast<UINT>(instBufSize), sizeof(InstanceData)};
    }
    return true;
  }

  void SceneRenderer::Uninitialize()
  {
    for (UINT i = 0; i < DeviceResources::kFrameCount; ++i)
    {
      if (m_instBuf[i] && m_instPtr[i])
      {
        m_instBuf[i]->Unmap(0, nullptr);
        m_instPtr[i] = nullptr;
      }
    }
  }

  // ---------------------------------------------------------------------------
  // SetShape — register the mesh (and optional diffuse) drawn for a catalog id.
  // Invalid meshes are ignored; a missing/invalid diffuse leaves the shape on the
  // untextured emissive path. Each diffuse gets its own SRV-heap slot.
  // ---------------------------------------------------------------------------
  void SceneRenderer::SetShape(uint16_t id, MeshGpu mesh, TextureGpu diffuse)
  {
    if (!mesh.valid() || !m_device) return;

    Shape shape;
    shape.mesh = std::move(mesh);

    if (diffuse.valid() && m_srvHeap && m_nextSrv < kMaxShapes)
    {
      shape.srvIndex = m_nextSrv++;
      shape.diffuse = std::move(diffuse);

      D3D12_CPU_DESCRIPTOR_HANDLE h = m_srvHeap->GetCPUDescriptorHandleForHeapStart();
      h.ptr += static_cast<SIZE_T>(shape.srvIndex) * m_srvDescSize;

      D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
      srv.Format = shape.diffuse.format;
      srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
      srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
      srv.Texture2D.MipLevels = shape.diffuse.mipCount ? shape.diffuse.mipCount : 1u;
      m_device->CreateShaderResourceView(shape.diffuse.resource.get(), &srv, h);
    }

    m_shapes[id] = std::move(shape);
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------
  void SceneRenderer::Render(ID3D12GraphicsCommandList* cl, const DirectX::XMFLOAT4X4& viewProj,
                             const SceneEntity* entities, uint32_t count)
  {
    // Select this frame's instance buffer (avoids racing the GPU on the buffer
    // still being read by the previous in-flight frame).
    const UINT fi = m_dr->FrameIndex();
    if (!count || !m_instPtr[fi]) return;
    count = (std::min)(count, kMaxEntities);

    NEURON_PIX_SCOPED(cl, PixColors::Scene, "Scene (%u instances)", count);

    // Group entities by shapeId so each registered mesh is drawn in one instanced
    // call. Sort a stable index list, fill the per-instance buffer in that order,
    // then issue one DrawRun per contiguous shapeId run (StartInstanceLocation
    // indexes into the shared instance buffer).
    std::array<uint32_t, kMaxEntities> order;
    for (uint32_t i = 0; i < count; ++i) order[i] = i;
    std::stable_sort(order.begin(), order.begin() + count,
                     [&](uint32_t a, uint32_t b) { return entities[a].shapeId < entities[b].shapeId; });

    for (uint32_t k = 0; k < count; ++k)
    {
      const auto& e = entities[order[k]];
      InstanceData& inst = m_instPtr[fi][k];

      // World matrix (scale × rotation around Y × translation), row-major.
      const float c = std::cos(e.yaw), s = std::sin(e.yaw);
      const float sc = e.scale;
      inst.world[0][0] = sc * c;
      inst.world[0][1] = 0.f;
      inst.world[0][2] = -sc * s;
      inst.world[0][3] = e.x;
      inst.world[1][0] = 0.f;
      inst.world[1][1] = sc;
      inst.world[1][2] = 0.f;
      inst.world[1][3] = e.y;
      inst.world[2][0] = sc * s;
      inst.world[2][1] = 0.f;
      inst.world[2][2] = sc * c;
      inst.world[2][3] = e.z;
      inst.world[3][0] = 0.f;
      inst.world[3][1] = 0.f;
      inst.world[3][2] = 0.f;
      inst.world[3][3] = 1.f;

      // Color: per-entity override if >= 0, else default by kind. (Only used by
      // the untextured path / as a tint; textured shapes sample their diffuse.)
      if (e.r >= 0.f)
      {
        inst.color[0] = e.r;
        inst.color[1] = e.g;
        inst.color[2] = e.b;
        inst.color[3] = 1.f;
      }
      else if (e.kind == static_cast<uint8_t>(1)) // Base
      {
        inst.color[0] = 0.f;
        inst.color[1] = 0.5f;
        inst.color[2] = 1.f;
        inst.color[3] = 1.f;
      }
      else
      {
        inst.color[0] = 1.f;
        inst.color[1] = 0.3f;
        inst.color[2] = 0.f;
        inst.color[3] = 1.f;
      }
    }

    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    if (m_srvHeap)
    {
      // Bind the shared SRV heap once; textured runs index into it per shape.
      ID3D12DescriptorHeap* heaps[] = {m_srvHeap.get()};
      cl->SetDescriptorHeaps(1, heaps);
    }

    uint32_t k = 0;
    while (k < count)
    {
      const uint16_t sid = entities[order[k]].shapeId;
      uint32_t start = k;
      while (k < count && entities[order[k]].shapeId == sid) ++k;
      DrawRun(cl, viewProj, sid, start, k - start, fi);
    }
  }

  // ---------------------------------------------------------------------------
  // DrawRun — draw [startInstance, startInstance+count) for one shapeId, choosing
  // the textured pipeline when the shape has a diffuse, else the untextured
  // emissive path; unregistered shapes fall back to the placeholder cube.
  // ---------------------------------------------------------------------------
  void SceneRenderer::DrawRun(ID3D12GraphicsCommandList* cl, const DirectX::XMFLOAT4X4& viewProj, uint16_t sid,
                              UINT startInstance, UINT count, UINT fi)
  {
    auto it = m_shapes.find(sid);
    const Shape* shape = (it != m_shapes.end() && it->second.mesh.valid()) ? &it->second : nullptr;
    const bool textured = shape && shape->diffuse.valid() && m_psoTex && m_srvHeap;

    if (textured)
    {
      cl->SetGraphicsRootSignature(m_rootSigTex.get());
      cl->SetPipelineState(m_psoTex.get());
      cl->SetGraphicsRoot32BitConstants(0, 16, &viewProj.m[0][0], 0);
      D3D12_GPU_DESCRIPTOR_HANDLE srv = m_srvHeap->GetGPUDescriptorHandleForHeapStart();
      srv.ptr += static_cast<UINT64>(shape->srvIndex) * m_srvDescSize;
      cl->SetGraphicsRootDescriptorTable(1, srv);
      cl->SetGraphicsRoot32BitConstants(2, 28, &m_light, 0); // b1 lighting
    }
    else
    {
      cl->SetGraphicsRootSignature(m_rootSig.get());
      cl->SetPipelineState(m_pso.get());
      cl->SetGraphicsRoot32BitConstants(0, 16, &viewProj.m[0][0], 0);
      cl->SetGraphicsRoot32BitConstants(1, 28, &m_light, 0); // b1 lighting
    }

    const D3D12_VERTEX_BUFFER_VIEW geomVb = shape ? shape->mesh.vbView : m_vbView;
    const D3D12_INDEX_BUFFER_VIEW geomIb = shape ? shape->mesh.ibView : m_ibView;
    const UINT geomIndexCount = shape ? shape->mesh.indexCount : m_indexCount;

    D3D12_VERTEX_BUFFER_VIEW vbViews[] = {geomVb, m_instView[fi]};
    cl->IASetVertexBuffers(0, 2, vbViews);
    cl->IASetIndexBuffer(&geomIb);
    cl->DrawIndexedInstanced(geomIndexCount, count, 0, 0, startInstance);
  }
} // namespace Neuron::Render
