// SceneRenderer.cpp — 3D instanced scene pass implementation.

#include "scene/SceneRenderer.h"
#include "gfx/DeviceResources.h"

// Compiled shader bytecode — generated by DXCCompile (NeuronRender.vcxproj).
// These headers are build artifacts; not checked into source control.
#include "CompiledShaders/SceneVS.h"
#include "CompiledShaders/ScenePS.h"

#include <DirectXMath.h>
#include <cmath>
#include <cstring>

using namespace DirectX;

namespace Neuron::Render
{

// ---------------------------------------------------------------------------
// Unit cube geometry (1m half-extent → callers apply scale in the world matrix)
// ---------------------------------------------------------------------------
// Face winding: front = CCW; cull mode = back.
// 24 vertices (4 unique per face × 6 faces), 36 indices.
static void FillCube(SceneRenderer::Vertex* verts, UINT16* idx)
{
    // Helper: add one quad (2 triangles, CCW front face)
    UINT16 vi = 0, ii = 0;
    auto quad = [&](float3 a, float3 b, float3 c, float3 d, float3 n)
    {
        UINT16 base = vi;
        for (auto& p : { a, b, c, d }) {
            verts[vi++] = { p.x, p.y, p.z, n.x, n.y, n.z };
        }
        idx[ii++] = base;     idx[ii++] = base + 1; idx[ii++] = base + 2;
        idx[ii++] = base;     idx[ii++] = base + 2; idx[ii++] = base + 3;
    };
    // +X face
    quad({1,-1, 1},{1, 1, 1},{1, 1,-1},{1,-1,-1},{1, 0, 0});
    // -X face
    quad({-1,-1,-1},{-1, 1,-1},{-1, 1, 1},{-1,-1, 1},{-1, 0, 0});
    // +Y face
    quad({-1, 1, 1},{ 1, 1, 1},{ 1, 1,-1},{-1, 1,-1},{ 0, 1, 0});
    // -Y face
    quad({-1,-1,-1},{ 1,-1,-1},{ 1,-1, 1},{-1,-1, 1},{ 0,-1, 0});
    // +Z face
    quad({-1,-1, 1},{ 1,-1, 1},{ 1, 1, 1},{-1, 1, 1},{ 0, 0, 1});
    // -Z face
    quad({ 1,-1,-1},{-1,-1,-1},{-1, 1,-1},{ 1, 1,-1},{ 0, 0,-1});
}

// ---------------------------------------------------------------------------
// Helper: create a GPU buffer from a CPU blob using a temporary upload heap.
// ---------------------------------------------------------------------------
static winrt::com_ptr<ID3D12Resource> CreateBufferWithData(
    ID3D12Device* device, ID3D12GraphicsCommandList* cl,
    const void* data, UINT64 size,
    D3D12_RESOURCE_STATES finalState,
    winrt::com_ptr<ID3D12Resource>& uploadOut)
{
    // Default heap (GPU only)
    D3D12_HEAP_PROPERTIES hpDefault{};
    hpDefault.Type = D3D12_HEAP_TYPE_DEFAULT;
    D3D12_RESOURCE_DESC rd{};
    rd.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    rd.Width     = size;
    rd.Height    = rd.DepthOrArraySize = rd.MipLevels = 1;
    rd.SampleDesc.Count = 1;
    rd.Layout    = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

    winrt::com_ptr<ID3D12Resource> buf;
    winrt::check_hresult(device->CreateCommittedResource(
        &hpDefault, D3D12_HEAP_FLAG_NONE, &rd,
        D3D12_RESOURCE_STATE_COPY_DEST, nullptr, IID_PPV_ARGS(buf.put())));

    // Upload heap (CPU write → GPU copy)
    D3D12_HEAP_PROPERTIES hpUpload{};
    hpUpload.Type = D3D12_HEAP_TYPE_UPLOAD;
    winrt::check_hresult(device->CreateCommittedResource(
        &hpUpload, D3D12_HEAP_FLAG_NONE, &rd,
        D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(uploadOut.put())));

    void* mapped = nullptr;
    D3D12_RANGE readRange{};
    winrt::check_hresult(uploadOut->Map(0, &readRange, &mapped));
    std::memcpy(mapped, data, size);
    uploadOut->Unmap(0, nullptr);

    cl->CopyResource(buf.get(), uploadOut.get());

    D3D12_RESOURCE_BARRIER rb{};
    rb.Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    rb.Transition.pResource   = buf.get();
    rb.Transition.StateBefore = D3D12_RESOURCE_STATE_COPY_DEST;
    rb.Transition.StateAfter  = finalState;
    rb.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    cl->ResourceBarrier(1, &rb);

    return buf;
}

// ---------------------------------------------------------------------------
// Initialize
// ---------------------------------------------------------------------------
bool SceneRenderer::Initialize(DeviceResources* dr)
{
    m_device = dr->Device();

    // --- Root signature: one entry — root constants (16 floats = 1 float4x4) ---
    D3D12_ROOT_PARAMETER param{};
    param.ParameterType             = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    param.ShaderVisibility          = D3D12_SHADER_VISIBILITY_VERTEX;
    param.Constants.ShaderRegister  = 0;
    param.Constants.RegisterSpace   = 0;
    param.Constants.Num32BitValues  = 16;

    D3D12_ROOT_SIGNATURE_DESC rsDesc{};
    rsDesc.NumParameters = 1;
    rsDesc.pParameters   = &param;
    rsDesc.Flags         = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    winrt::com_ptr<ID3DBlob> sigBlob, errBlob;
    if (FAILED(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
                                           sigBlob.put(), errBlob.put())))
        return false;
    winrt::check_hresult(m_device->CreateRootSignature(
        0, sigBlob->GetBufferPointer(), sigBlob->GetBufferSize(),
        IID_PPV_ARGS(m_rootSig.put())));

    // --- Input layout ---
    static constexpr D3D12_INPUT_ELEMENT_DESC kLayout[] = {
        // Stream 0: per-vertex
        { "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT,    0,  0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,   0 },
        { "NORMAL",   0, DXGI_FORMAT_R32G32B32_FLOAT,    0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,   0 },
        // Stream 1: per-instance (world matrix rows w0-w3 + color)
        { "TEXCOORD", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1,  0, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1 },
        { "TEXCOORD", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 16, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1 },
        { "TEXCOORD", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 32, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1 },
        { "TEXCOORD", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 48, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1 },
        { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, 64, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA, 1 },
    };

    // --- PSO ---
    D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc{};
    psoDesc.pRootSignature        = m_rootSig.get();
    psoDesc.VS                    = { g_pSceneVS, sizeof(g_pSceneVS) };
    psoDesc.PS                    = { g_pScenePS, sizeof(g_pScenePS) };
    psoDesc.InputLayout           = { kLayout, static_cast<UINT>(std::size(kLayout)) };
    psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    psoDesc.NumRenderTargets      = 1;
    psoDesc.RTVFormats[0]         = DXGI_FORMAT_B8G8R8A8_UNORM;
    psoDesc.DSVFormat             = DXGI_FORMAT_D32_FLOAT;
    psoDesc.SampleDesc.Count      = 1;

    // Rasterizer: solid, back-face cull
    psoDesc.RasterizerState.FillMode              = D3D12_FILL_MODE_SOLID;
    psoDesc.RasterizerState.CullMode              = D3D12_CULL_MODE_BACK;
    psoDesc.RasterizerState.FrontCounterClockwise = FALSE;
    psoDesc.RasterizerState.DepthClipEnable       = TRUE;

    // Blend: opaque
    psoDesc.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;

    // Depth: test + write
    psoDesc.DepthStencilState.DepthEnable    = TRUE;
    psoDesc.DepthStencilState.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ALL;
    psoDesc.DepthStencilState.DepthFunc      = D3D12_COMPARISON_FUNC_LESS;

    winrt::check_hresult(m_device->CreateGraphicsPipelineState(
        &psoDesc, IID_PPV_ARGS(m_pso.put())));

    // --- Upload geometry via a temporary command list ---
    // (Caller runs us inside the frame's command list which is open at Initialize time;
    //  we re-open and execute a separate one to keep the geometry upload atomic.)
    winrt::com_ptr<ID3D12CommandAllocator> uploadAlloc;
    winrt::check_hresult(m_device->CreateCommandAllocator(
        D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(uploadAlloc.put())));
    winrt::com_ptr<ID3D12GraphicsCommandList> uploadCl;
    winrt::check_hresult(m_device->CreateCommandList(
        0, D3D12_COMMAND_LIST_TYPE_DIRECT,
        uploadAlloc.get(), nullptr, IID_PPV_ARGS(uploadCl.put())));

    // Build cube CPU data
    static Vertex cubeVerts[24];
    static UINT16 cubeIdx[36];
    FillCube(cubeVerts, cubeIdx);
    m_indexCount = 36;

    winrt::com_ptr<ID3D12Resource> vbUpload, ibUpload;
    m_vb = CreateBufferWithData(m_device, uploadCl.get(),
                                cubeVerts, sizeof(cubeVerts),
                                D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER,
                                vbUpload);
    m_ib = CreateBufferWithData(m_device, uploadCl.get(),
                                cubeIdx, sizeof(cubeIdx),
                                D3D12_RESOURCE_STATE_INDEX_BUFFER,
                                ibUpload);

    winrt::check_hresult(uploadCl->Close());

    // Execute and wait for the upload to complete
    winrt::com_ptr<ID3D12CommandQueue> tmpQueue;
    D3D12_COMMAND_QUEUE_DESC qd{}; qd.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
    winrt::check_hresult(m_device->CreateCommandQueue(&qd, IID_PPV_ARGS(tmpQueue.put())));
    ID3D12CommandList* lists[] = { uploadCl.get() };
    tmpQueue->ExecuteCommandLists(1, lists);
    winrt::com_ptr<ID3D12Fence> fence;
    winrt::check_hresult(m_device->CreateFence(0, D3D12_FENCE_FLAG_NONE, IID_PPV_ARGS(fence.put())));
    HANDLE ev = CreateEventW(nullptr, FALSE, FALSE, nullptr);
    winrt::check_hresult(tmpQueue->Signal(fence.get(), 1));
    winrt::check_hresult(fence->SetEventOnCompletion(1, ev));
    WaitForSingleObjectEx(ev, INFINITE, FALSE);
    CloseHandle(ev);

    // Set up static VB/IB views
    m_vbView  = { m_vb->GetGPUVirtualAddress(), sizeof(cubeVerts), sizeof(Vertex) };
    m_ibView  = { m_ib->GetGPUVirtualAddress(), sizeof(cubeIdx), DXGI_FORMAT_R16_UINT };

    // --- Per-instance upload buffer (CPU-mapped, written each frame) ---
    constexpr UINT64 instBufSize = kMaxEntities * sizeof(InstanceData);
    D3D12_HEAP_PROPERTIES hpUpload{};
    hpUpload.Type = D3D12_HEAP_TYPE_UPLOAD;
    D3D12_RESOURCE_DESC instDesc{};
    instDesc.Dimension        = D3D12_RESOURCE_DIMENSION_BUFFER;
    instDesc.Width            = instBufSize;
    instDesc.Height = instDesc.DepthOrArraySize = instDesc.MipLevels = 1;
    instDesc.SampleDesc.Count = 1;
    instDesc.Layout           = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    winrt::check_hresult(m_device->CreateCommittedResource(
        &hpUpload, D3D12_HEAP_FLAG_NONE, &instDesc,
        D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(m_instBuf.put())));
    D3D12_RANGE readRange{};
    winrt::check_hresult(m_instBuf->Map(0, &readRange,
        reinterpret_cast<void**>(&m_instPtr)));

    m_instView = { m_instBuf->GetGPUVirtualAddress(),
                   static_cast<UINT>(instBufSize),
                   sizeof(InstanceData) };
    return true;
}

void SceneRenderer::Uninitialize()
{
    if (m_instBuf && m_instPtr) { m_instBuf->Unmap(0, nullptr); m_instPtr = nullptr; }
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------
void SceneRenderer::Render(ID3D12GraphicsCommandList* cl,
                           const float viewProjT[16],
                           const SceneEntity* entities, uint32_t count)
{
    if (!count || !m_instPtr) return;
    count = std::min(count, kMaxEntities);

    // Fill per-instance buffer.
    for (uint32_t i = 0; i < count; ++i) {
        const auto& e = entities[i];
        InstanceData& inst = m_instPtr[i];

        // World matrix (scale × rotation around Y × translation), row-major.
        const float c = std::cos(e.yaw),  s = std::sin(e.yaw);
        const float sc = e.scale;
        inst.world[0][0] =  sc * c;   inst.world[0][1] = 0.f; inst.world[0][2] = -sc * s; inst.world[0][3] = e.x;
        inst.world[1][0] = 0.f;        inst.world[1][1] = sc;  inst.world[1][2] = 0.f;      inst.world[1][3] = e.y;
        inst.world[2][0] =  sc * s;   inst.world[2][1] = 0.f; inst.world[2][2] =  sc * c;  inst.world[2][3] = e.z;
        inst.world[3][0] = 0.f;        inst.world[3][1] = 0.f; inst.world[3][2] = 0.f;      inst.world[3][3] = 1.f;

        // Color: use per-entity override if >= 0, else default by kind.
        if (e.r >= 0.f) {
            inst.color[0] = e.r; inst.color[1] = e.g; inst.color[2] = e.b; inst.color[3] = 1.f;
        } else if (e.kind == 0) { // Base: neon blue
            inst.color[0] = 0.f; inst.color[1] = 0.5f; inst.color[2] = 1.f; inst.color[3] = 1.f;
        } else {                  // Ship: orange
            inst.color[0] = 1.f; inst.color[1] = 0.3f; inst.color[2] = 0.f; inst.color[3] = 1.f;
        }
    }

    // Record draw commands.
    cl->SetGraphicsRootSignature(m_rootSig.get());
    cl->SetPipelineState(m_pso.get());
    cl->SetGraphicsRoot32BitConstants(0, 16, viewProjT, 0);
    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    D3D12_VERTEX_BUFFER_VIEW vbViews[] = { m_vbView, m_instView };
    cl->IASetVertexBuffers(0, 2, vbViews);
    cl->IASetIndexBuffer(&m_ibView);
    cl->DrawIndexedInstanced(m_indexCount, count, 0, 0, 0);
}

} // namespace Neuron::Render
